/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FoodIcons {
  FoodIcons._();

  static const _kFontFam = 'FoodIcons';

  static const IconData breakfast = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData burger = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData fish_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData corn = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData diet = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData meat = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData pasta = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData fast_food = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData coffee_cup_1 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData fork = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData coffee_cup = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData harvest_1 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData pizza = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData fish = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData jamaican_jerk_chicken = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData dish = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData apple = const IconData(0xe812, fontFamily: _kFontFam);
}
